---
name: Run python tests
on: ["push", "pull_request"]  # yamllint disable-line rule:truthy

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["py311", "py312", "py313"]

        steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
        - name: Set up Python ${{ matrix.python-version }}
          uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7  # v10.2.0
        - name: Install tox
          run: uv tool install tox --with tox-uv
        - name: run tests
          run: uv tool run tox -e ${{ matrix.python-version }}
